### PR TITLE
Fix FF06h to be TMA

### PR DESCRIPTION
**Pull request by mark-riley**
Hi, I noticed a typo in the docs. I thought I'd offer a fix. I didn't generate the PDF. I don't know if you do anything special there.

As this is a binary file and you can't see the diff, I changed

5.3. FF06h – TIMA – Timer Modulo (R/W)

to

5.3. FF06h – TMA – Timer Modulo (R/W)

### CODE REVIEW

**Comment by AntonioND** [comment]
This is certainly a horrible format to check diffs. :(

**Comment by mark-riley** [comment]
I suppose if you don't want to go through the hassle of checking to make sure I haven't vandalised the document, you could search for
FF06h – TIMA – Timer Modulo (R/W)
make sure that changing it to TMA is correct, make the change yourself and then commit. You don't know me from Joe and you've put a lot of work into this. I'm pretty sure you wouldn't want someone putting in random nonsense. 

Basically, you have both FF05 and FF06 as TIMA, and I'm pretty sure FF06 should be TMA.

**Comment by AntonioND** [comment]
I could do it and set you as author or co-author of the commit.

To be fair, it is my fault for choosing a format that can't be reviewed with git. In my defense, I did this a long time ago and I barely knew how to use git... :laughing: Maybe I should spend some time and move everything to ``.rst``, I just didn't expect people to be using this after all this time...

I wanted to do a release at some point, that's why I moved the build system to CMake. However, it looks like even with CMake it's not trivial to build it on Windows... Anyway, just some random thoughts I have.

**Comment by mark-riley** [comment]
There's no need for that. I don't need my name in the log.

I've been messing with cmake and windows recently. I'll take a look at it if you like? It isn't trivial as you say. I had to set system variables for SDL on my emulator.

As for moving to rST, I can give you a hand. I'm spending a lot of time looking at your docs, so I should be able to asist.

**Comment by AntonioND** [comment]
I've added you as "Reported-by:" in https://github.com/AntonioND/giibiiadvance/commit/fae4d9c7c9627b9a18b3ddf4e410c7b987ff02f7

Regarding the rst files... I think this lockdown is going to last for a long time, I need something to entertain myself. At least I want to create the initial documents.

Regarding windows, I'm trying at the moment with https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=vs-2019 and if it works I'll add the instructions to the readme. The problem is OpenCV. The other libraries are easy.

**Pull request closed without merging**
